apiVersion: v1
kind: Secret
metadata:
  name: app-secrets
  namespace: 3-tier
type: Opaque
stringData:
  DB_URL: "mongodb+srv://dishantsaini993_db_user:T2WnNP9tlBW0sDaR@3tier.0byhijf.mongodb.net/?appName=3tier"
  SECRET: "Dishant"
  CLOUDINARY_CLOUD_NAME: 'a4jerltj'
  CLOUDINARY_KEY: '195282894366959'
  CLOUDINARY_SECRET: 'Da655LMKTPIRMO0mzhhm5mJQuTQ'
  MAPBOX_TOKEN: "<your-mapbox-token>"